import sqlmodel

"""Added tracking and tracking_filter tables

Revision ID: 70d137bc1056
Revises: 
Create Date: 2025-02-21 11:28:50.511741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d137bc1056'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackingfilter',
    sa.Column('from_airport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_airport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cabin_class', sa.Enum('ECONOMY_CLASS', 'BUSINESS_CLASS', name='cabin_type_enum'), nullable=False),
    sa.Column('trip_type', sa.Enum('ONE_WAY', 'RETURN', name='trip_type_enum'), nullable=False),
    sa.Column('fly_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('nb_adults', sa.Integer(), nullable=False),
    sa.Column('nb_children', sa.Integer(), nullable=False),
    sa.Column('nb_infants_in_seat', sa.Integer(), nullable=False),
    sa.Column('nb_infants_on_lap', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracking_id'], ['tracking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trackingfilter')
    op.drop_table('tracking')
    # ### end Alembic commands ###
