import sqlmodel

"""Move out price column from tracking_filter to tracking table

Revision ID: 83d7871a5fa9
Revises: 70d137bc1056
Create Date: 2025-02-21 15:16:56.852311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d7871a5fa9'
down_revision: Union[str, None] = '70d137bc1056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('price', sa.Float(), nullable=False))
    op.drop_column('trackingfilter', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackingfilter', sa.Column('price', sa.FLOAT(), nullable=False))
    op.drop_column('tracking', 'price')
    # ### end Alembic commands ###
