import sqlmodel

"""add resolved column to tracking table to manage resolving trackings

Revision ID: ad4ad2d23e44
Revises: ee50ff521173
Create Date: 2025-03-08 00:23:19.439162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4ad2d23e44'
down_revision: Union[str, None] = 'ee50ff521173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('resolved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'resolved')
    # ### end Alembic commands ###
