import sqlmodel

"""Update column trip_type (change one_way enum value with one-way) from table trackingfilter 

Revision ID: ee50ff521173
Revises: 83d7871a5fa9
Create Date: 2025-02-22 23:15:00.634648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee50ff521173'
down_revision: Union[str, None] = '83d7871a5fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
